services:
    yahoo_japan_config_cache.component.config_cache:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\ConfigCache
        # The arguments will be added by DefinitionDecorator
        calls:
            - [setArrayAccess, ['@yahoo_japan_config_cache.component.array_access']]
        public: false
        lazy: true

    yahoo_japan_config_cache.component.php_file_cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments:
            # The first argument will be replaced by DefinitionDecorator
            - ''
            - '.php'
        public: false

    yahoo_japan_config_cache.component.array_access:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Util\ArrayAccess

    yahoo_japan_config_cache.component.delegating_loader:
        class: Symfony\Component\Config\Loader\DelegatingLoader
        arguments:
            - '@yahoo_japan_config_cache.component.resolver'

    yahoo_japan_config_cache.component.resolver:
        class: Symfony\Component\Config\Loader\LoaderResolver
        arguments:
            -
                - '@yahoo_japan_config_cache.component.yaml_file_loader'
                - '@yahoo_japan_config_cache.component.xml_file_loader'
        public: false

    yahoo_japan_config_cache.component.yaml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Loader\YamlFileLoader
        public: false

    yahoo_japan_config_cache.component.xml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Loader\XmlFileLoader
        public: false
