services:
    yahoo_japan_config_cache.array_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Locale\Loader\ArrayLoader
        arguments: ['@translator.default']

    yahoo_japan_config_cache.yaml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Locale\Loader\YamlFileLoader
        calls:
            - [addLoader, ['@yahoo_japan_config_cache.array_loader']]

    yahoo_japan_config_cache.config_cache_listener:
        class: YahooJapan\ConfigCacheBundle\EventListener\ConfigCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: %yahoo_japan_config_cache.listener_priority% }
