services:
    yahoo_japan_config_cache.array_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Locale\Loader\ArrayLoader
        arguments: ['@translator.default']

    yahoo_japan_config_cache.yaml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Locale\Loader\YamlFileLoader
        calls:
            - [addLoader, ['@yahoo_japan_config_cache.array_loader']]

    yahoo_japan_config_cache.locale_listener:
        class: YahooJapan\ConfigCacheBundle\EventListener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: %yahoo_japan_config_cache.listener_priority% }

    yahoo_japan_config_cache.cache_warmer:
        class: YahooJapan\ConfigCacheBundle\CacheWarmer\CacheWarmer
        tags:
            - { name: kernel.cache_warmer, priority: 0 }

    yahoo_japan_config_cache.component.config_cache:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\ConfigCache
        # The arguments and tags will be added by DefinitionDecorator
        calls:
            - [setArrayAccess, ['@yahoo_japan_config_cache.component.array_access']]
        public: false
        lazy: true

    yahoo_japan_config_cache.component.php_file_cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments:
            # The first argument will be replaced by DefinitionDecorator
            - ''
            - '.php'
        public: false

    yahoo_japan_config_cache.component.array_access:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Util\ArrayAccess

    yahoo_japan_config_cache.component.delegating_loader:
        class: Symfony\Component\Config\Loader\DelegatingLoader
        arguments:
            - '@yahoo_japan_config_cache.component.resolver'

    yahoo_japan_config_cache.component.resolver:
        class: Symfony\Component\Config\Loader\LoaderResolver
        arguments:
            -
                - '@yahoo_japan_config_cache.component.yaml_file_loader'
                - '@yahoo_japan_config_cache.component.xml_file_loader'
        public: false

    yahoo_japan_config_cache.component.yaml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Loader\YamlFileLoader
        public: false

    yahoo_japan_config_cache.component.xml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Loader\XmlFileLoader
        public: false
