services:
    yahoo_japan_config_cache.locale.array_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Locale\Loader\ArrayLoader
        arguments: ['@translator.default']

    yahoo_japan_config_cache.locale.yaml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Locale\Loader\YamlFileLoader
        calls:
            - [addLoader, ['@yahoo_japan_config_cache.locale.array_loader']]

    yahoo_japan_config_cache.locale.listener:
        class: YahooJapan\ConfigCacheBundle\EventListener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: %yahoo_japan_config_cache.listener_priority% }

    yahoo_japan_config_cache.cache_restorer:
        class: YahooJapan\ConfigCacheBundle\CacheWarmer\CacheRestorer
        tags:
            - { name: kernel.cache_warmer, priority: 1 }

    yahoo_japan_config_cache.cache_warmer:
        class: YahooJapan\ConfigCacheBundle\CacheWarmer\CacheWarmer
        tags:
            - { name: kernel.cache_warmer, priority: 0 }

    yahoo_japan_config_cache.cache_cleanup:
        class: YahooJapan\ConfigCacheBundle\CacheWarmer\CacheCleanup
        arguments:
            - '@yahoo_japan_config_cache.filesystem'
        tags:
            - { name: kernel.cache_warmer, priority: -1 }

    yahoo_japan_config_cache.cache_saver:
        class: YahooJapan\ConfigCacheBundle\CacheClearer\CacheSaver
        tags:
            - { name: kernel.cache_clearer, priority: 0 }

    yahoo_japan_config_cache.config_cache:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\ConfigCache
        # The arguments and tags will be added by DefinitionDecorator
        calls:
            - [setArrayAccess, ['@yahoo_japan_config_cache.array_access']]
        public: false
        lazy: true

    yahoo_japan_config_cache.php_file_cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments:
            # The first argument will be replaced by DefinitionDecorator
            - ''
            - '.php'
        public: false

    yahoo_japan_config_cache.restorable_php_file_cache:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\RestorablePhpFileCache
        parent: yahoo_japan_config_cache.php_file_cache
        calls:
            - [setFilesystem, ['@yahoo_japan_config_cache.filesystem']]

    yahoo_japan_config_cache.filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    yahoo_japan_config_cache.array_access:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Util\ArrayAccess

    yahoo_japan_config_cache.delegating_loader:
        class: Symfony\Component\Config\Loader\DelegatingLoader
        arguments:
            - '@yahoo_japan_config_cache.resolver'

    yahoo_japan_config_cache.resolver:
        class: Symfony\Component\Config\Loader\LoaderResolver
        arguments:
            -
                - '@yahoo_japan_config_cache.yaml_file_loader'
                - '@yahoo_japan_config_cache.xml_file_loader'
        public: false

    yahoo_japan_config_cache.yaml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Loader\YamlFileLoader
        public: false

    yahoo_japan_config_cache.xml_file_loader:
        class: YahooJapan\ConfigCacheBundle\ConfigCache\Loader\XmlFileLoader
        public: false
